# Generated by Django 2.2.16 on 2022-06-06 06:43

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220606_1040'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follower',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(user=django.db.models.expressions.F('following')), name='unique_follower'),
        ),
    ]
