# Generated by Django 2.2.16 on 2022-06-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220606_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follower',
        ),
    ]
